# Generated by Django 5.1.5 on 2025-01-28 01:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shared_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("post_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
