# Generated by Django 5.1.5 on 2025-01-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_remove_post_id_alter_post_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
