# Generated by Django 5.1.5 on 2025-01-29 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("component", "0001_initial"),
        ("post", "0003_alter_post_post_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="post_id",
            field=models.ForeignKey(
                default=5, on_delete=django.db.models.deletion.CASCADE, to="post.post"
            ),
            preserve_default=False,
        ),
    ]
